export const mockUsers = {
  currentUser: {
    id: '12345',
    name: 'Rajesh Kumar',
    username: '@rajesh_k',
    email: 'rajesh@email.com',
    phone: '+91 98765 43210',
    dob: '1990-03-15',
    gender: 'Male',
    rating: 4.8,
    totalReviews: 120,
    totalTrips: 45,
    totalEarnings: 12500,
    totalSpent: 8900,
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    vehicles: [
      {
        id: 'v1',
        type: 'Car',
        brand: 'Honda City',
        number: 'KA-01-AB-1234',
        plateType: 'white',
        photos: {
          front: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400',
          back: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400',
        },
        insuranceExpiry: '2025-12-31',
        status: 'active',
      },
    ],
    documents: {
      drivingLicense: { front: 'verified', back: 'verified' },
      aadhar: { front: 'verified', back: 'verified' },
      vehicle: 'verified',
    },
    verificationStatus: 'verified',
  },
};

export const mockPoolingOffers = [
  {
    id: 'pool1',
    driverId: '12345',
    driverName: 'Rajesh K.',
    driverPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    rating: 4.8,
    totalReviews: 120,
    route: {
      from: 'Bangalore',
      to: 'Mumbai',
      fromLat: 12.9716,
      fromLng: 77.5946,
      toLat: 19.0760,
      toLng: 72.8777,
    },
    date: '2024-01-15',
    time: '09:00',
    vehicle: {
      type: 'Car',
      brand: 'Honda City',
      number: 'KA-01-AB-1234',
      photos: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400'],
    },
    availableSeats: 2,
    totalSeats: 4,
    price: 450,
    notes: 'Non-smoking, AC available, luggage space available',
    passengers: [
      { id: 'p1', name: 'Ravi', status: 'confirmed' },
      { id: 'p2', name: 'Sneha', status: 'confirmed' },
    ],
    status: 'active',
    views: 45,
    bookingRequests: 3,
  },
  {
    id: 'pool2',
    driverId: '67890',
    driverName: 'Priya M.',
    driverPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    rating: 4.9,
    totalReviews: 89,
    route: {
      from: 'Delhi',
      to: 'Jaipur',
      fromLat: 28.6139,
      fromLng: 77.2090,
      toLat: 26.9124,
      toLng: 75.7873,
    },
    date: '2024-01-16',
    time: '10:30',
    vehicle: {
      type: 'Car',
      brand: 'Maruti Swift',
      number: 'DL-01-AB-5678',
      photos: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400'],
    },
    availableSeats: 1,
    totalSeats: 3,
    price: 500,
    notes: 'Comfortable ride, music system',
    passengers: [
      { id: 'p3', name: 'Amit', status: 'confirmed' },
      { id: 'p4', name: 'Suresh', status: 'confirmed' },
    ],
    status: 'active',
    views: 32,
    bookingRequests: 2,
  },
  {
    id: 'pool3',
    driverId: '11111',
    driverName: 'Amit S.',
    driverPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    rating: 4.7,
    totalReviews: 56,
    route: {
      from: 'Pune',
      to: 'Mumbai',
      fromLat: 18.5204,
      fromLng: 73.8567,
      toLat: 19.0760,
      toLng: 72.8777,
    },
    date: '2024-01-17',
    time: '11:00',
    vehicle: {
      type: 'Bike',
      brand: 'Royal Enfield',
      number: 'MH-12-AB-9012',
      photos: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=400'],
    },
    availableSeats: 0,
    totalSeats: 1,
    price: 300,
    notes: 'Helmet provided',
    passengers: [
      { id: 'p5', name: 'Rohit', status: 'confirmed' },
    ],
    status: 'active',
    views: 28,
    bookingRequests: 1,
  },
];

export const mockRentalOffers = [
  {
    id: 'rent1',
    ownerId: '67890',
    ownerName: 'Priya M.',
    ownerPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    rating: 4.9,
    totalReviews: 89,
    vehicle: {
      type: 'Car',
      brand: 'Honda City',
      year: 2022,
      number: 'KA-02-CD-5678',
      seats: 5,
      fuel: 'Petrol',
      transmission: 'Manual',
      photos: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400',
      ],
    },
    location: {
      address: '123 Main Street, Bangalore',
      lat: 12.9716,
      lng: 77.5946,
    },
    date: '2024-01-15',
    availableFrom: '10:00',
    availableUntil: '18:00',
    pricePerHour: 800,
    minimumHours: 2,
    notes: 'Well maintained, clean vehicle',
    totalBookings: 12,
    completed: 10,
    cancelled: 2,
    revenue: 96000,
    status: 'active',
  },
  {
    id: 'rent2',
    ownerId: 'company1',
    ownerName: 'ABC Car Rentals',
    ownerPhoto: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400',
    rating: 4.7,
    totalReviews: 234,
    vehicle: {
      type: 'Car',
      brand: 'Maruti Swift',
      year: 2021,
      number: 'KA-03-EF-9012',
      seats: 5,
      fuel: 'Petrol',
      transmission: 'Manual',
      photos: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400',
      ],
    },
    location: {
      address: '456 Tech Park, Mumbai',
      lat: 19.0760,
      lng: 72.8777,
    },
    date: '2024-01-16',
    availableFrom: '09:00',
    availableUntil: '20:00',
    pricePerHour: 600,
    minimumHours: 2,
    notes: 'Company vehicle, reliable service',
    totalBookings: 45,
    completed: 42,
    cancelled: 3,
    revenue: 234000,
    status: 'active',
  },
];

export const mockBookings = [
  {
    id: 'booking1',
    bookingId: '#YA20240115001',
    type: 'pooling',
    route: {
      from: 'Bangalore',
      to: 'Mumbai',
    },
    date: '2024-01-15',
    time: '09:00',
    driver: {
      name: 'Rajesh K.',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      phone: '+91 98765 43210',
    },
    vehicle: {
      type: 'Car',
      brand: 'Honda City',
      number: 'KA-01-AB-1234',
    },
    amount: 450,
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    status: 'confirmed',
    passengers: [
      { name: 'You', status: 'confirmed' },
      { name: 'Ravi', status: 'confirmed' },
      { name: 'Sneha', status: 'confirmed' },
    ],
  },
  {
    id: 'booking2',
    bookingId: '#YA20240112001',
    type: 'rental',
    vehicle: {
      type: 'Car',
      brand: 'Honda City',
      number: 'KA-02-CD-5678',
    },
    date: '2024-01-12',
    duration: 4,
    amount: 3200,
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    status: 'completed',
    owner: {
      name: 'Priya M.',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    },
  },
  {
    id: 'booking3',
    bookingId: '#YA20240110001',
    type: 'pooling',
    route: {
      from: 'Delhi',
      to: 'Jaipur',
    },
    date: '2024-01-10',
    time: '08:00',
    status: 'cancelled',
    amount: 500,
  },
];

export const mockNotifications = [
  {
    id: 'notif1',
    type: 'booking_request',
    title: 'New booking request',
    message: 'Ravi wants to join your pool',
    time: '2 hours ago',
    read: false,
    actionRequired: true,
  },
  {
    id: 'notif2',
    type: 'booking_confirmed',
    title: 'Booking confirmed',
    message: 'Your rental booking is confirmed',
    time: '5 hours ago',
    read: false,
    actionRequired: false,
  },
  {
    id: 'notif3',
    type: 'rating_request',
    title: 'Rate your experience',
    message: 'How was your trip with Rajesh?',
    time: '1 day ago',
    read: false,
    actionRequired: true,
  },
];

export const mockFeedback = [
  {
    id: 'fb1',
    type: 'payment_issue',
    user: 'Rajesh K.',
    userId: '12345',
    subject: 'Payment not reflected',
    description: 'Payment was made but not credited to account',
    status: 'pending',
    priority: 'high',
    submitted: '2024-01-15T10:30:00',
  },
  {
    id: 'fb2',
    type: 'feature_suggestion',
    user: 'Priya M.',
    userId: '67890',
    subject: 'Add recurring trips feature',
    description: 'Would be great to have recurring trip booking',
    status: 'acknowledged',
    priority: 'medium',
    submitted: '2024-01-14T15:45:00',
  },
];

export const mockChatMessages = [
  {
    id: '1',
    text: 'Hi, is the pool still available?',
    sender: 'other',
    time: '10:30 AM',
  },
  {
    id: '2',
    text: 'Yes, 2 seats available',
    sender: 'me',
    time: '10:32 AM',
  },
  {
    id: '3',
    text: "Great! I'll join. What's the pickup point?",
    sender: 'other',
    time: '10:35 AM',
  },
  {
    id: '4',
    text: 'Location shared',
    sender: 'me',
    time: '10:36 AM',
    type: 'location',
    location: { lat: 12.9716, lng: 77.5946, address: '123 Main Street, Bangalore' },
  },
];

export const mockMyOffers = [
  {
    id: '1',
    type: 'pooling',
    route: { from: 'Bangalore', to: 'Mumbai' },
    date: '2024-01-15',
    time: '9:00 AM',
    status: 'active',
    seatsBooked: 2,
    totalSeats: 4,
  },
  {
    id: '2',
    type: 'rental',
    vehicle: 'Honda City',
    duration: '4 hours',
    date: '2024-01-16',
    time: '10:00 AM',
    status: 'booked',
    bookedBy: 'Ravi',
  },
  {
    id: '3',
    type: 'pooling',
    route: { from: 'Delhi', to: 'Jaipur' },
    date: '2024-01-10',
    time: '8:00 AM',
    status: 'completed',
  },
];
